language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.1
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28
	licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - ./gradlew test
after_success:
  - bash <(curl -s https://codecov.io/bash)
