language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-28
  - extra-android-m2repository
script:
  - ./gradlew test
after_success:
  - bash <(curl -s https://codecov.io/bash)
